version: '3'
services:
  db:
    image: postgres:14.2
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: container_db
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
  UI:
    image: dpage/pgadmin4
    ports:
      - 2000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ahmadwaseem648@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ahmad123
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  ML:
    image: muhammad648/traffic-detection:v1.0-cuda11.0
    stdin_open: true
    tty: true
    depends_on:
     - db
    environment:
        STREAM_SOURCE: ./video/v2.mp4
        TIME_SLAB: 0.1
    network_mode: "host"
volumes:
  postgres-data:
  pgadmin-data:
